version: '3.7'

networks:
  kafka:
      name: kafka_network
      driver: bridge 

services:
  systemstats:
    build:
      context: ./system-stats
    container_name: systemstats
    env_file:
      - .env
    ports:
      - "${SYSTEM_STATS_PORT}:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks: 
      - kafka
  consumer:
    build:
      context: ./consumer
    container_name: consumer
    env_file:
      - .env
    ports:
      - "${CONSUMER_PORT}:${INTERNAL_PORT}"
    networks: 
      - kafka

  producer:
    build:
      context: ./producer
    container_name: producer
    env_file:
      - .env
    ports:
      - "${PRODUCER_PORT}:${INTERNAL_PORT}"
    networks: 
      - kafka

  ui:
    container_name: dashboard-ui
    build:
      context: ./dashboard
    env_file:
      - .env
    ports:
      - "${WEB_UI_PORT}:80"
    networks: 
      - kafka

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    hostname: broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./run_workaround.sh:/tmp/run_workaround.sh
    ports:
      - "9092:9092"
      - "9101:9101"
    command: >
      bash -c "chmod +x /tmp/run_workaround.sh &&
               /tmp/run_workaround.sh && /etc/confluent/docker/run"
    networks: 
      - kafka
    